//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeManagement.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        public string CMConnectionString {
            get {
                return ((string)(this["CMConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-EF65QNAB\\SQLEXPRESS01;Initial Catalog=C:\\USERS\\OWNER\\DESKTOP\\P" +
            "ROJECTCUOIKY\\COFFEEMANAGEMENT\\CM.MDF;Integrated Security=True;Encrypt=True;Trust" +
            "ServerCertificate=True")]
        public string C__USERS_OWNER_DESKTOP_PROJECTCUOIKY_COFFEEMANAGEMENT_CM_MDFConnectionString {
            get {
                return ((string)(this["C__USERS_OWNER_DESKTOP_PROJECTCUOIKY_COFFEEMANAGEMENT_CM_MDFConnectionString"]));
            }
        }
    }
}
